# Generated by Django 6.0.6 on 2026-06-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApp', '0004_alter_auditlog_action_category_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a global sub-category visible to everyone. Select a user to make this sub-category visible only to that user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_subcategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name', 'user')},
        ),
    ]
