# Generated by Django 6.0.6 on 2026-06-15 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApp', '0005_alter_subcategory_unique_together_subcategory_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for a global sub-category visible to everyone. Select one or more users to make this sub-category visible only to them.', related_name='private_subcategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
