# Generated by Django 6.0.6 on 2026-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashApp', '0006_alter_subcategory_unique_together_subcategory_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_dynamic',
            field=models.BooleanField(default=False),
        ),
    ]
